@startuml

skinparam sequenceArrowThickness 1
skinparam roundcorner 20

interface ISrvHandler {
}


class SrvHandlerAddEmployee<component> implements ISrvHandler {
    - DataRepository repository
    - public String addEmployee(EmployeeRequest employeeRequest)
}

class SrvHandlerDeleteEmployee<component> implements ISrvHandler {
    - DataRepository repository
    - public void deleteEmployee(String employeeId)
}

class SrvHandlerGetAllEmployees<component> implements ISrvHandler {
    - DataRepository repository
    - public List<EmployeeDTO> getAllEmployees()
}

class SrvHandlerGetEmployee<component> implements ISrvHandler {
    - DataRepository repository
    - public EmployeeDTO getEmployee(String id)
}

class SrvHandlerUpdateEmployee<component> implements ISrvHandler {
    - DataRepository repository
    - public void updateEmployee(String id, EmployeeRequest request)
}

@enduml
